// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6CepjfM5Id9W4IiDEaoa5GQVNP6FYM1c',
    appId: '1:710358199568:web:1528a10d305cf84508c995',
    messagingSenderId: '710358199568',
    projectId: 'pdamappchat',
    authDomain: 'pdamappchat.firebaseapp.com',
    storageBucket: 'pdamappchat.firebasestorage.app',
    measurementId: 'G-W9VRSPJGVN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUnBISbubnsEfGiWbqCA1Kksunxs6RIAQ',
    appId: '1:710358199568:android:15fe51e9958d922308c995',
    messagingSenderId: '710358199568',
    projectId: 'pdamappchat',
    storageBucket: 'pdamappchat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAnSXC5D3n2VQFRNnJdXtVg3URi3qEYz4',
    appId: '1:710358199568:ios:69c1c3f02944022108c995',
    messagingSenderId: '710358199568',
    projectId: 'pdamappchat',
    storageBucket: 'pdamappchat.firebasestorage.app',
    iosBundleId: 'com.example.pdamApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAnSXC5D3n2VQFRNnJdXtVg3URi3qEYz4',
    appId: '1:710358199568:ios:69c1c3f02944022108c995',
    messagingSenderId: '710358199568',
    projectId: 'pdamappchat',
    storageBucket: 'pdamappchat.firebasestorage.app',
    iosBundleId: 'com.example.pdamApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6CepjfM5Id9W4IiDEaoa5GQVNP6FYM1c',
    appId: '1:710358199568:web:a8e6894a379a21d908c995',
    messagingSenderId: '710358199568',
    projectId: 'pdamappchat',
    authDomain: 'pdamappchat.firebaseapp.com',
    storageBucket: 'pdamappchat.firebasestorage.app',
    measurementId: 'G-WRRSMRNK6G',
  );

}